user_input = input("Enter a comma-separated string: ")
input_list = user_input.split(',')
letters = list(filter(lambda x: x.isalpha(), input_list))
uppercase_letters = list(map(lambda x: x.upper(), letters))
digits = list(filter(lambda x: x.isdigit(), input_list))
squared_digits = list(map(lambda x: int(x) ** 2, digits))
alphanumeric = list(filter(lambda x: x.isalnum(), input_list))
print("Uppercase letters:", uppercase_letters)
print("Squared digits:", squared_digits)
print("Alphanumeric characters:", alphanumeric)
